import './Contenedores.css';

export const portadas = [
  {nombre: 'Abbey Road', foto: '/Imagenes/AbbeyRoad.jpg', categoria: 'Rock', indexCateg: 1, respuestaCorrecta: false},
  {nombre: 'Atom Heart Mother', foto: '/Imagenes/AHM.jpg', categoria: 'Rock', indexCateg: 1, respuestaCorrecta: false},
  {nombre: 'AM', foto: '/Imagenes/Am.png', categoria: 'Rock', indexCateg: 1, respuestaCorrecta: false},
  {nombre: 'Californication', foto: '/Imagenes/Californication.jpg', categoria: 'Rock', indexCateg: 1, respuestaCorrecta: false},
  {nombre: 'El Silencio', foto: '/Imagenes/ElSilencio.jpg', categoria: 'Rock', indexCateg: 1, respuestaCorrecta: false},
  {nombre: 'In Utero', foto: '/Imagenes/InUtero.jpg', categoria: 'Rock', indexCateg: 1, respuestaCorrecta: false},
  {nombre: 'Mezmerize', foto: '/Imagenes/Mezmerize.jpg', categoria: 'Rock', indexCateg: 1, respuestaCorrecta: false},
  {nombre: 'Rammstein', foto: '/Imagenes/Rammstein.jpg', categoria: 'Rock', indexCateg: 1, respuestaCorrecta: false},
  {nombre: 'The Dark Side of the Moon', foto: '/Imagenes/TDSOTM.png', categoria: 'Rock', indexCateg: 1, respuestaCorrecta: false},
  {nombre: 'Funky kingston', foto: '/Imagenes/FunkyKingston.jpg', categoria: 'Reggae', indexCateg: 2, respuestaCorrecta: false},
  {nombre: 'Kaya', foto: '/Imagenes/Kaya.jpg', categoria: 'Reggae', indexCateg: 2, respuestaCorrecta: false},
  {nombre: 'Marcus Garvey', foto: '/Imagenes/MarcusGarvey.jpg', categoria: 'Reggae', indexCateg: 2, respuestaCorrecta: false},
  {nombre: 'Trenchtown Mix Up', foto: '/Imagenes/TrenchtownMixUp.jpg', categoria: 'Reggae', indexCateg: 2, respuestaCorrecta: false},
  {nombre: 'Super Ape', foto: '/Imagenes/SuperApe.jpg', categoria: 'Reggae', indexCateg: 2, respuestaCorrecta: false},
  {nombre: 'Distant Relative', foto: '/Imagenes/DistantRelative.jpg', categoria: 'Reggae', indexCateg: 2, respuestaCorrecta: false},
  {nombre: 'Best Dressed Chicken In Town', foto: '/Imagenes/BDCIT.jpg', categoria: 'Reggae', indexCateg: 2, respuestaCorrecta: false},
  {nombre: 'Conquering Lion', foto: '/Imagenes/ConqueringLion.jpg', categoria: 'Reggae', indexCateg: 2, respuestaCorrecta: false},
  {nombre: 'King Tubbys Presents Soundclash Dubplate Style', foto: '/Imagenes/KTPSD.jpg', categoria: 'Reggae', indexCateg: 2, respuestaCorrecta: false},
  {nombre: 'Shawn Mendes', foto: '/Imagenes/ShawnMendes.png', categoria: 'Pop', indexCateg: 3, respuestaCorrecta: false},
  {nombre: 'Caution', foto: '/Imagenes/Caution.png', categoria: 'Pop', indexCateg: 3, respuestaCorrecta: false},
  {nombre: 'Bloom', foto: '/Imagenes/Bloom.jpg', categoria: 'Pop', indexCateg: 3, respuestaCorrecta: false},
  {nombre: 'Dancing Queen', foto: '/Imagenes/DancingQueen.jpg', categoria: 'Pop', indexCateg: 3, respuestaCorrecta: false},
  {nombre: 'Sweetener', foto: '/Imagenes/Sweetener.png', categoria: 'Pop', indexCateg: 3, respuestaCorrecta: false},
  {nombre: 'Golden', foto: '/Imagenes/Golden.png', categoria: 'Pop', indexCateg: 3, respuestaCorrecta: false},
  {nombre: 'Voicenotes', foto: '/Imagenes/Voicenotes.jpg', categoria: 'Pop', indexCateg: 3, respuestaCorrecta: false},
  {nombre: 'Liberation', foto: '/Imagenes/Liberation.png', categoria: 'Pop', indexCateg: 3, respuestaCorrecta: false},
  {nombre: 'Thriller', foto: '/Imagenes/Thriller.jpg', categoria: 'Pop', indexCateg: 3, respuestaCorrecta: false},
  {nombre: 'The Marshall Mathers LP', foto: '/Imagenes/TheMarshallMathersLP.jpg', categoria: 'Rap/HipHop', indexCateg: 4, respuestaCorrecta: false},
  {nombre: 'Me Against The World', foto: '/Imagenes/MeAgainstTheWorld.jpg', categoria: 'Rap/HipHop', indexCateg: 4, respuestaCorrecta: false},
  {nombre: 'The Eminem Show', foto: '/Imagenes/TheEminemShow.jpg', categoria: 'Rap/HipHop', indexCateg: 4, respuestaCorrecta: false},
  {nombre: 'All Eyez On Me', foto: '/Imagenes/AllEyezOnMe.jpg', categoria: 'Rap/HipHop', indexCateg: 4, respuestaCorrecta: false},
  {nombre: 'Stillmatic', foto: '/Imagenes/Stillmatic.jpg', categoria: 'Rap/HipHop', indexCateg: 4, respuestaCorrecta: false},
  {nombre: 'Black On Both Sides', foto: '/Imagenes/BlackOnBothSides.jpg', categoria: 'Rap/HipHop', indexCateg: 4, respuestaCorrecta: false},
  {nombre: 'Black Sunday', foto: '/Imagenes/BlackSunday.jpg', categoria: 'Rap/HipHop', indexCateg: 4, respuestaCorrecta: false},
  {nombre: 'Things Fall Apart', foto: '/Imagenes/ThingsFallApart.jpg', categoria: 'Rap/HipHop', indexCateg: 4, respuestaCorrecta: false},
  {nombre: 'Aquemini', foto: '/Imagenes/Aquemini.jpg', categoria: 'Rap/HipHop', indexCateg: 4, respuestaCorrecta: false}
];